name: Build Spring Boot

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Spring Boot
        run: ./mvnw clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/*.jar